version: '3.7'

services:
  db:
    image: mongo:7.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - main-network

  init-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: init-color-my-country-db
    depends_on:
      - db
    

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: API
    depends_on:
      - init-db
    ports: 
      8080:8080
    networks:
      - main-network
    #The API's startup logic should check that the test user exists
    #and the count of the counties is correct.

volumes:
  mongo-data:
#allows the containers to communicate with eachother
networks:
  main-network:
    driver: bridge